apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/base/tailscale-proxy-groups/config
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: control-cluster-proxy
      - op: replace
        path: /spec/tags/0
        value: tag:k8s
    target:
      kind: ProxyGroup
      name: placeholder-name
