[project]
name = "homelab-pulumi"
version = "0.1.0"
dependencies = [
    "pulumi>=3.0.0",
    "pulumi-kubernetes>=4.0.0",
    "parver",
    "semver",
    "pyyaml",
    "requests",
    "typing-extensions"
]
