apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    http:
      addr: :5000
      secret: localdevsecret
      headers:
        X-Content-Type-Options: [nosniff]
    storage:
      s3:
        region: us-east-1
        regionendpoint: http://10.43.202.112:3900
        bucket: docker-dev
        secure: false
        v4auth: true
        rootdirectory: /
