apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.0.6/manifests/ha/install.yaml
- cmp-configmaps.yaml

patches:
- path: patch-kustomized-helm-cmp.yaml
- path: patch-pulumi-cmp.yaml

images:
  - name: quay.io/argoproj/argocd
    newTag: v3.0.6
